### ISSUE TITLE
Provide option to log to stdout

### ISSUE THREAD

**Issue by tongpu** [Huawei/eSDK_K8S_Plugin#26]
The way the logging stack for `huawei-csi` is currently set up all logs are written to `/var/log/huawei` and no information is visible when using `kubectl logs`.

This additionally also leads to the issue that when running on OpenShift the controller needs to be run with a privileged security context, because it needs to run as root:root to be able to log to `/var/log/huawei`.

**Comment by juliohm1978** [comment]
Since we still need to build the Docker image ourselves, we managed to redirect logs to stdout by just linking log files to /dev/stdout. In your Dockerfile:

```Dockerfile
RUN mkdir -p /var/log/huawei \
 && ln -s /dev/stdout /var/log/huawei/huawei-csi-controller \
 && ln -s /dev/stdout /var/log/huawei/huawei-csi-node
```

And in your manifests do deploy, comment out every occurrance of /var/log mounts.

![image](https://user-images.githubusercontent.com/4145456/132757730-6f6c23c5-d6e0-4aa8-9c2b-6c7a6f290ca2.png)

**Comment by pbabilas** [comment]
all you need to do is set param - "--loggingModule=console" in args of huawei-csi-driver ;]
